version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
      day: monday
      time: "04:17"
      timezone: Europe/Prague
    groups:
      development-tooling:
        dependency-type: development
        patterns: ["*"]
    labels: [dependencies, python]
    commit-message:
      prefix: deps
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: monday
      time: "04:37"
      timezone: Europe/Prague
    groups:
      github-actions:
        patterns: ["*"]
    labels: [dependencies, github-actions]
    commit-message:
      prefix: ci
    open-pull-requests-limit: 5
